name=PTSolns_I2Connect_EEPROM
version=1.0.3
author=PTSolns
maintainer=PTSolns
sentence=Arduino library for the PTSolns I2Connect EEPROM module.
paragraph=Provides simple read, write, update, String, array, and struct storage helpers for the PTSolns I2Connect EEPROM module using I2C.
category=Data Storage
url=https://github.com/PTSolns/I2Connect_EEPROM
architectures=*
includes=PTSolns_I2Connect_EEPROM.h
